#include "media_stubs.h"
#include <stdlib.h>
#include <string.h>
#include <sys/types.h>

const char *AMEDIAFORMAT_KEY_CHANNEL_COUNT="channel-count",*AMEDIAFORMAT_KEY_COLOR_FORMAT="color-format",*AMEDIAFORMAT_KEY_COLOR_RANGE="color-range",*AMEDIAFORMAT_KEY_COLOR_STANDARD="color-standard",*AMEDIAFORMAT_KEY_DURATION="durationUs",*AMEDIAFORMAT_KEY_ENCODER_DELAY="encoder-delay",*AMEDIAFORMAT_KEY_FRAME_RATE="frame-rate",*AMEDIAFORMAT_KEY_HEIGHT="height",*AMEDIAFORMAT_KEY_LANGUAGE="language",*AMEDIAFORMAT_KEY_MIME="mime",*AMEDIAFORMAT_KEY_ROTATION="rotation-degrees",*AMEDIAFORMAT_KEY_SAMPLE_RATE="sample-rate",*AMEDIAFORMAT_KEY_SLICE_HEIGHT="slice-height",*AMEDIAFORMAT_KEY_STRIDE="stride",*AMEDIAFORMAT_KEY_WIDTH="width";
typedef struct{int dummy;} Obj; static void*obj_new(void){return calloc(1,sizeof(Obj));}
void AHardwareBuffer_describe(void*b,void*d){(void)b;if(d)memset(d,0,64);} void AHardwareBuffer_release(void*b){(void)b;}
int AImageReader_newWithUsage(int32_t w,int32_t h,int32_t f,int32_t m,uint64_t u,void**out){(void)w;(void)h;(void)f;(void)m;(void)u;if(out)*out=obj_new();return 0;} void AImageReader_delete(void*r){free(r);} int AImageReader_getWindow(void*r,void**w){(void)r;if(w)*w=NULL;return 0;} int AImageReader_acquireLatestImage(void*r,void**i){(void)r;if(i)*i=NULL;return -1;} int AImageReader_setImageListener(void*r,void*l){(void)r;(void)l;return 0;} int AImageReader_setBufferRemovedListener(void*r,void*l){(void)r;(void)l;return 0;}
void AImage_delete(void*i){free(i);} void AImage_deleteAsync(void*i,int fd){(void)fd;free(i);} int AImage_getHardwareBuffer(void*i,void**b){(void)i;if(b)*b=NULL;return -1;} int AImage_getTimestamp(void*i,int64_t*t){(void)i;if(t)*t=0;return 0;} int AImage_getWidth(void*i,int32_t*w){(void)i;if(w)*w=0;return 0;}
void AMediaFormat_delete(void*f){free(f);} int AMediaFormat_getInt32(void*f,const char*k,int32_t*v){(void)f;(void)k;if(v)*v=0;return 0;} int AMediaFormat_getInt64(void*f,const char*k,int64_t*v){(void)f;(void)k;if(v)*v=0;return 0;} int AMediaFormat_getFloat(void*f,const char*k,float*v){(void)f;(void)k;if(v)*v=0;return 0;} int AMediaFormat_getString(void*f,const char*k,const char**v){(void)f;(void)k;if(v)*v="";return 0;} void AMediaFormat_setInt32(void*f,const char*k,int32_t v){(void)f;(void)k;(void)v;}
void*AMediaCodec_createDecoderByType(const char*t){(void)t;return NULL;} int AMediaCodec_delete(void*c){free(c);return 0;} int AMediaCodec_configure(void*c,void*f,void*w,void*cr,uint32_t flags){(void)c;(void)f;(void)w;(void)cr;(void)flags;return -1;} int AMediaCodec_start(void*c){(void)c;return -1;} int AMediaCodec_stop(void*c){(void)c;return 0;} int AMediaCodec_flush(void*c){(void)c;return 0;} long AMediaCodec_dequeueInputBuffer(void*c,int64_t t){(void)c;(void)t;return -1;} uint8_t*AMediaCodec_getInputBuffer(void*c,size_t i,size_t*n){(void)c;(void)i;if(n)*n=0;return NULL;} int AMediaCodec_queueInputBuffer(void*c,size_t i,off_t o,size_t s,uint64_t t,uint32_t f){(void)c;(void)i;(void)o;(void)s;(void)t;(void)f;return -1;} long AMediaCodec_dequeueOutputBuffer(void*c,void*i,int64_t t){(void)c;(void)i;(void)t;return -1;} uint8_t*AMediaCodec_getOutputBuffer(void*c,size_t i,size_t*n){(void)c;(void)i;if(n)*n=0;return NULL;} void*AMediaCodec_getOutputFormat(void*c){(void)c;return NULL;} int AMediaCodec_releaseOutputBuffer(void*c,size_t i,int r){(void)c;(void)i;(void)r;return 0;} int AMediaCodec_setOutputSurface(void*c,void*w){(void)c;(void)w;return -1;}
void*AMediaExtractor_new(void){return obj_new();} void AMediaExtractor_delete(void*e){free(e);} int AMediaExtractor_setDataSourceFd(void*e,int fd,long o,long l){(void)e;(void)fd;(void)o;(void)l;return -1;} int AMediaExtractor_setDataSource(void*e,const char*u,const char*const*h){(void)e;(void)u;(void)h;return -1;} int AMediaExtractor_setDataSourceCustom(void*e,void*d){(void)e;(void)d;return -1;} size_t AMediaExtractor_getTrackCount(void*e){(void)e;return 0;} void*AMediaExtractor_getTrackFormat(void*e,size_t i){(void)e;(void)i;return NULL;} int AMediaExtractor_selectTrack(void*e,size_t i){(void)e;(void)i;return -1;} long AMediaExtractor_readSampleData(void*e,uint8_t*b,size_t n){(void)e;(void)b;(void)n;return -1;} int AMediaExtractor_advance(void*e){(void)e;return 0;} int64_t AMediaExtractor_getSampleTime(void*e){(void)e;return -1;} int AMediaExtractor_getSampleTrackIndex(void*e){(void)e;return -1;} int AMediaExtractor_seekTo(void*e,int64_t p,int m){(void)e;(void)p;(void)m;return 0;}
void*AMediaDataSource_new(void){return obj_new();} void AMediaDataSource_delete(void*d){free(d);} void AMediaDataSource_setUserdata(void*d,void*u){(void)d;(void)u;} void AMediaDataSource_setReadAt(void*d,void*f){(void)d;(void)f;} void AMediaDataSource_setGetSize(void*d,void*f){(void)d;(void)f;} void AMediaDataSource_setClose(void*d,void*f){(void)d;(void)f;}

#define M(x) if(!strcmp(name,#x))return (uintptr_t)&x
uintptr_t media_lookup(const char *name){ if(!name)return 0;
    if(!strcmp(name,"AMEDIAFORMAT_KEY_CHANNEL_COUNT")) return (uintptr_t)&AMEDIAFORMAT_KEY_CHANNEL_COUNT;
    if(!strcmp(name,"AMEDIAFORMAT_KEY_COLOR_FORMAT")) return (uintptr_t)&AMEDIAFORMAT_KEY_COLOR_FORMAT;
    if(!strcmp(name,"AMEDIAFORMAT_KEY_COLOR_RANGE")) return (uintptr_t)&AMEDIAFORMAT_KEY_COLOR_RANGE;
    if(!strcmp(name,"AMEDIAFORMAT_KEY_COLOR_STANDARD")) return (uintptr_t)&AMEDIAFORMAT_KEY_COLOR_STANDARD;
    if(!strcmp(name,"AMEDIAFORMAT_KEY_DURATION")) return (uintptr_t)&AMEDIAFORMAT_KEY_DURATION;
    if(!strcmp(name,"AMEDIAFORMAT_KEY_ENCODER_DELAY")) return (uintptr_t)&AMEDIAFORMAT_KEY_ENCODER_DELAY;
    if(!strcmp(name,"AMEDIAFORMAT_KEY_FRAME_RATE")) return (uintptr_t)&AMEDIAFORMAT_KEY_FRAME_RATE;
    if(!strcmp(name,"AMEDIAFORMAT_KEY_HEIGHT")) return (uintptr_t)&AMEDIAFORMAT_KEY_HEIGHT;
    if(!strcmp(name,"AMEDIAFORMAT_KEY_LANGUAGE")) return (uintptr_t)&AMEDIAFORMAT_KEY_LANGUAGE;
    if(!strcmp(name,"AMEDIAFORMAT_KEY_MIME")) return (uintptr_t)&AMEDIAFORMAT_KEY_MIME;
    if(!strcmp(name,"AMEDIAFORMAT_KEY_ROTATION")) return (uintptr_t)&AMEDIAFORMAT_KEY_ROTATION;
    if(!strcmp(name,"AMEDIAFORMAT_KEY_SAMPLE_RATE")) return (uintptr_t)&AMEDIAFORMAT_KEY_SAMPLE_RATE;
    if(!strcmp(name,"AMEDIAFORMAT_KEY_SLICE_HEIGHT")) return (uintptr_t)&AMEDIAFORMAT_KEY_SLICE_HEIGHT;
    if(!strcmp(name,"AMEDIAFORMAT_KEY_STRIDE")) return (uintptr_t)&AMEDIAFORMAT_KEY_STRIDE;
    if(!strcmp(name,"AMEDIAFORMAT_KEY_WIDTH")) return (uintptr_t)&AMEDIAFORMAT_KEY_WIDTH;
    M(AHardwareBuffer_describe);M(AHardwareBuffer_release);M(AImageReader_newWithUsage);M(AImageReader_delete);M(AImageReader_getWindow);M(AImageReader_acquireLatestImage);M(AImageReader_setImageListener);M(AImageReader_setBufferRemovedListener);M(AImage_delete);M(AImage_deleteAsync);M(AImage_getHardwareBuffer);M(AImage_getTimestamp);M(AImage_getWidth);M(AMediaFormat_delete);M(AMediaFormat_getInt32);M(AMediaFormat_getInt64);M(AMediaFormat_getFloat);M(AMediaFormat_getString);M(AMediaFormat_setInt32);M(AMediaCodec_createDecoderByType);M(AMediaCodec_delete);M(AMediaCodec_configure);M(AMediaCodec_start);M(AMediaCodec_stop);M(AMediaCodec_flush);M(AMediaCodec_dequeueInputBuffer);M(AMediaCodec_getInputBuffer);M(AMediaCodec_queueInputBuffer);M(AMediaCodec_dequeueOutputBuffer);M(AMediaCodec_getOutputBuffer);M(AMediaCodec_getOutputFormat);M(AMediaCodec_releaseOutputBuffer);M(AMediaCodec_setOutputSurface);M(AMediaExtractor_new);M(AMediaExtractor_delete);M(AMediaExtractor_setDataSourceFd);M(AMediaExtractor_setDataSource);M(AMediaExtractor_setDataSourceCustom);M(AMediaExtractor_getTrackCount);M(AMediaExtractor_getTrackFormat);M(AMediaExtractor_selectTrack);M(AMediaExtractor_readSampleData);M(AMediaExtractor_advance);M(AMediaExtractor_getSampleTime);M(AMediaExtractor_getSampleTrackIndex);M(AMediaExtractor_seekTo);M(AMediaDataSource_new);M(AMediaDataSource_delete);M(AMediaDataSource_setUserdata);M(AMediaDataSource_setReadAt);M(AMediaDataSource_setGetSize);M(AMediaDataSource_setClose);
    return 0; }
#undef M
